import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { kidlifeColors as C, kidlifeLayout as L } from '@/theme';

const groups = { 'Đồ ăn': [['🍎', 'Táo đỏ', 3], ['🍪', 'Bánh quy', 5], ['🍰', 'Bánh kem', 10], ['🍕', 'Pizza', 8], ['🍔', 'Burger', 9], ['🍣', 'Sushi', 12], ['🍜', 'Mì ramen', 6], ['🌽', 'Bắp ngô', 4]], 'Trang phục': [['🧢', 'Mũ len', 6], ['👕', 'Áo xanh', 7], ['🎈', 'Bóng bay', 5], ['👟', 'Giày thể thao', 9], ['🧤', 'Găng tay', 6], ['🧣', 'Khăn len', 8]], 'Nội thất': [['🛏️', 'Giường nhỏ', 12], ['🛁', 'Bồn tắm', 10], ['🪑', 'Ghế gỗ', 5], ['📺', 'Tivi', 15], ['🪴', 'Cây xanh', 7], ['🪆', 'Đồ trang trí', 9]] } as const;
type Category = keyof typeof groups;
export default function StoreScreen() { const [category, setCategory] = useState<Category>('Đồ ăn'); const [coins, setCoins] = useState(9); const [owned, setOwned] = useState<string[]>([]); return <ScrollView style={L.screen} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text style={styles.title}>Cửa hàng</Text><Text style={styles.subtitle}>Mang những điều vui về cho Bun Bun</Text></View><View style={styles.coins}><Ionicons name="star" size={16} color={C.orange} /><Text style={styles.coinsText}>{coins}</Text></View></View><View style={styles.tabs}>{(Object.keys(groups) as Category[]).map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.tab, category === item && styles.tabActive]}><Text style={[styles.tabText, category === item && styles.tabTextActive]}>{item}</Text></Pressable>)}</View><View style={styles.grid}>{groups[category].map(([icon, name, cost]) => <Pressable key={name} style={[styles.item, owned.includes(name) && styles.itemOwned]} onPress={() => { if (!owned.includes(name) && coins >= cost) { setCoins(coins - cost); setOwned([...owned, name]); } }}><Text style={styles.itemIcon}>{icon}</Text><Text style={styles.itemName}>{name}</Text><View style={styles.cost}><Ionicons name={owned.includes(name) ? 'checkmark' : 'star'} size={12} color={owned.includes(name) ? C.green : C.orange} /><Text style={[styles.costText, owned.includes(name) && { color: C.green }]}>{owned.includes(name) ? 'Đã có' : cost}</Text></View></Pressable>)}</View><View style={styles.tip}><Text style={styles.tipEmoji}>💡</Text><Text style={styles.tipText}>Hoàn thành nhiệm vụ để kiếm thêm XP và mua đồ cho thú cưng nhé!</Text></View></ScrollView>; }
const styles = StyleSheet.create({ content: { ...L.content, paddingTop: 8 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 19 }, title: { color: C.text, fontSize: 28, fontWeight: '800' }, subtitle: { color: C.muted, fontSize: 12, marginTop: 4 }, coins: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.orangeSoft, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 9 }, coinsText: { color: '#B36A00', fontSize: 14, fontWeight: '900' }, tabs: { flexDirection: 'row', gap: 7, marginBottom: 18 }, tab: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 11, backgroundColor: C.surface }, tabActive: { backgroundColor: C.primary }, tabText: { color: C.muted, fontSize: 11, fontWeight: '700' }, tabTextActive: { color: '#FFF' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, item: { width: '23.5%', minHeight: 106, backgroundColor: C.lime, borderRadius: 13, alignItems: 'center', justifyContent: 'center', padding: 7 }, itemOwned: { backgroundColor: C.greenSoft }, itemIcon: { fontSize: 30 }, itemName: { color: C.text, fontSize: 9, fontWeight: '700', textAlign: 'center', marginTop: 5 }, cost: { flexDirection: 'row', gap: 3, alignItems: 'center', marginTop: 5 }, costText: { color: '#B36A00', fontSize: 10, fontWeight: '900' }, tip: { flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: C.primarySoft, borderRadius: 13, padding: 12, marginTop: 22 }, tipEmoji: { fontSize: 21 }, tipText: { color: C.primary, fontSize: 11, lineHeight: 16, flex: 1 } });
