import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { Routes } from '@/navigation/constants';
import { kidlifeColors as C } from '@/theme';

export const RegisterScreen = () => { const navigation = useNavigation<any>(); const [form, setForm] = useState({ username: '', password: '', name: '', phone: '', email: '' }); const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value })); return <ScrollView style={styles.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable style={styles.back} onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={20} color={C.primary} /></Pressable><View style={styles.form}><Text style={styles.title}>Đăng ký</Text><Text style={styles.subtitle}>Tạo tài khoản mới ngay</Text><Field icon="person-outline" label="Tên đăng nhập" placeholder="Tên đăng nhập..." value={form.username} onChangeText={(value) => update('username', value)} /><Field icon="lock-closed-outline" label="Mật khẩu" placeholder="Mật khẩu..." value={form.password} onChangeText={(value) => update('password', value)} secureTextEntry /><Field icon="person-outline" label="Họ và tên" placeholder="Họ và tên..." value={form.name} onChangeText={(value) => update('name', value)} /><Field icon="call-outline" label="Số điện thoại" placeholder="Số điện thoại..." value={form.phone} onChangeText={(value) => update('phone', value)} /><Field icon="mail-outline" label="Email" placeholder="Email..." value={form.email} onChangeText={(value) => update('email', value)} /><Pressable style={styles.primaryButton} onPress={() => navigation.navigate(Routes.Auth.OTP, { email: form.email })}><Text style={styles.buttonText}>Đăng ký</Text></Pressable></View></ScrollView>; };
function Field({ icon, label, placeholder, secureTextEntry, value, onChangeText }: { icon: any; label: string; placeholder: string; secureTextEntry?: boolean; value: string; onChangeText: (value: string) => void }) { return <View style={styles.fieldWrap}><Text style={styles.label}>{label}</Text><View style={styles.field}><Ionicons name={icon} size={18} color={C.primary} /><TextInput style={styles.input} placeholder={placeholder} placeholderTextColor="#9DA9D8" value={value} onChangeText={onChangeText} secureTextEntry={secureTextEntry} /></View></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F5F7FF' }, content: { minHeight: '100%', paddingHorizontal: 20 }, back: { width: 42, height: 42, borderRadius: 22, backgroundColor: '#E4E9FF', alignItems: 'center', justifyContent: 'center', marginTop: 16 }, form: { marginTop: 32, paddingBottom: 28 }, title: { color: '#102980', fontSize: 28, fontWeight: '900', textAlign: 'center' }, subtitle: { color: '#A4ADD0', fontSize: 12, textAlign: 'center', marginTop: 5, marginBottom: 25 }, fieldWrap: { marginBottom: 13 }, label: { color: '#17328B', fontSize: 12, fontWeight: '800', marginBottom: 6 }, field: { height: 47, borderRadius: 15, backgroundColor: '#E7EBFF', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14 }, input: { flex: 1, color: C.text, fontSize: 12, marginLeft: 9 }, primaryButton: { height: 53, borderRadius: 28, backgroundColor: '#2445FF', alignItems: 'center', justifyContent: 'center', marginTop: 7 }, buttonText: { color: '#FFF', fontSize: 13, fontWeight: '900' } });
