// Mock data cho module "Kiểm Tra Trí Nhớ" (Quiz Module)
// TODO: Replace with API call → GET /api/quizsets?category=...
import { QuizSet } from '@/shared/types/quiz';

export const INITIAL_QUIZ_SETS: QuizSet[] = [
  {
    id: 'quiz-1',
    title: 'Cách đánh răng đúng cách',
    description: 'Bé học cách giữ gìn răng miệng luôn thơm tho và sáng bóng mỗi ngày.',
    category: 've_sinh',
    categoryLabel: 'Vệ sinh',
    ageRange: '4-6 tuổi',
    emoji: '🦷',
    questionCount: 5,
    reward_xp: 30,
    pass_score: 70,
    time_per_question: 30,
    difficulty: 'easy',
    questions: [
      {
        id: 'q1-1',
        question: 'Bé nên đánh răng mấy lần mỗi ngày để vi khuẩn không tấn công răng?',
        options: [
          { id: 'opt-a', text: 'Chỉ 1 lần vào buổi trưa' },
          { id: 'opt-b', text: 'Ít nhất 2 lần: Sáng sau khi dậy và Tối trước khi đi ngủ' },
          { id: 'opt-c', text: 'Không cần đánh răng nếu súc nước' },
          { id: 'opt-d', text: '1 tuần chỉ đánh răng 1 lần' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Đánh răng sáng và tối giúp loại bỏ mảng bám và ngăn ngừa sâu răng hiệu quả nhất!',
      },
      {
        id: 'q1-2',
        question: 'Thời gian tối thiểu bé nên chải răng trong mỗi lần là bao lâu?',
        options: [
          { id: 'opt-a', text: '10 giây là xong ngay' },
          { id: 'opt-b', text: 'Khoảng 2 phút (chải đủ mọi mặt răng)' },
          { id: 'opt-c', text: '10 phút không nghỉ' },
          { id: 'opt-d', text: '30 phút' },
        ],
        correct_answer: 'opt-b',
        explanation: '2 phút là thời gian tiêu chuẩn để chải sạch mặt trước, mặt sau và mặt nhai của cả hàm răng.',
      },
      {
        id: 'q1-3',
        question: 'Lượng kem đánh răng bé nên lấy trên bàn chải to cỡ nào?',
        options: [
          { id: 'opt-a', text: 'Đầy cả bàn chải tràn ra ngoài' },
          { id: 'opt-b', text: 'Bằng một hạt đậu nhỏ xíu' },
          { id: 'opt-c', text: 'Bằng quả trứng gà' },
          { id: 'opt-d', text: 'Không cần lấy kem' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Lượng kem bằng một hạt đậu nhỏ là vừa đủ an toàn và bảo vệ men răng cho bé.',
      },
      {
        id: 'q1-4',
        question: 'Khi đánh răng, bé nên chải theo chiều nào là tốt nhất cho nướu?',
        options: [
          { id: 'opt-a', text: 'Chà ngang thật mạnh bạo' },
          { id: 'opt-b', text: 'Chải nhẹ nhàng xoay tròn hoặc dọc theo kẽ răng' },
          { id: 'opt-c', text: 'Chỉ ngậm bàn chải không cần di chuyển' },
          { id: 'opt-d', text: 'Cắn chặt bàn chải' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Chải dọc hoặc xoay tròn nhẹ nhàng giúp làm sạch kẽ răng mà không làm tổn thương nướu.',
      },
      {
        id: 'q1-5',
        question: 'Sau khi đánh răng xong, bé cần làm gì tiếp theo?',
        options: [
          { id: 'opt-a', text: 'Nuốt luôn bọt kem đánh răng' },
          { id: 'opt-b', text: 'Súc miệng sạch bằng nước và rửa sạch bàn chải' },
          { id: 'opt-c', text: 'Đi ngủ ngay mà không nhổ kem' },
          { id: 'opt-d', text: 'Ăn thêm một cái kẹo ngọt' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Bé nhớ nhổ sạch bọt kem, súc miệng nước sạch và cắm bàn chải thẳng đứng ở nơi khô ráo nhé!',
      },
    ],
  },
  {
    id: 'quiz-2',
    title: 'Tự gấp quần áo gọn gàng',
    description: 'Rèn luyện tính tự lập bằng cách tự sắp xếp trang phục ngăn nắp.',
    category: 'tu_lap',
    categoryLabel: 'Tự lập',
    ageRange: '6-8 tuổi',
    emoji: '👕',
    questionCount: 4,
    reward_xp: 25,
    pass_score: 75,
    time_per_question: 30,
    difficulty: 'medium',
    questions: [
      {
        id: 'q2-1',
        question: 'Trước khi bắt đầu gấp một chiếc áo phông, bé nên trải áo ở đâu?',
        options: [
          { id: 'opt-a', text: 'Vo tròn ném xuống sàn nhà' },
          { id: 'opt-b', text: 'Trải phẳng phiu mặt lưng trên giường hoặc mặt bàn sạch' },
          { id: 'opt-c', text: 'Treo lơ lửng trên quạt trần' },
          { id: 'opt-d', text: 'Nhét vào xô giặt đồ' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Trải phẳng áo giúp các nếp gấp ngay ngắn, áo không bị nhăn nhúm.',
      },
      {
        id: 'q2-2',
        question: 'Bước tiếp theo khi gấp áo phông là gì?',
        options: [
          { id: 'opt-a', text: 'Cắt bỏ hai ống tay áo' },
          { id: 'opt-b', text: 'Gấp hai bên mép áo và tay áo vào giữa' },
          { id: 'opt-c', text: 'Kéo căng thật mạnh' },
          { id: 'opt-d', text: 'Vo lại thành quả bóng' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Gấp đều hai mép và tay áo vào trong giúp tạo thành hình chữ nhật gọn gàng.',
      },
      {
        id: 'q2-3',
        question: 'Sau khi gấp quần áo xong, bé nên cất chúng vào đâu?',
        options: [
          { id: 'opt-a', text: 'Xếp ngay ngắn vào ngăn tủ quần áo của bé' },
          { id: 'opt-b', text: 'Vứt bừa bãi dưới gầm giường' },
          { id: 'opt-c', text: 'Bỏ vào thùng rác' },
          { id: 'opt-d', text: 'Để ở ghế sofa phòng khách' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Xếp quần áo vào ngăn tủ riêng giúp phòng ngủ gọn gàng và dễ tìm khi cần mặc.',
      },
      {
        id: 'q2-4',
        question: 'Việc tự gấp quần áo mang lại lợi ích gì cho bé?',
        options: [
          { id: 'opt-a', text: 'Làm bé mệt mỏi và chán nản' },
          { id: 'opt-b', text: 'Giúp bé rèn tính tự lập, ngăn nắp và giúp đỡ ba mẹ' },
          { id: 'opt-c', text: 'Không có lợi ích gì cả' },
          { id: 'opt-d', text: 'Làm hỏng hết quần áo' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Tự lập làm việc nhỏ mỗi ngày là bước đầu để trở thành em bé ngoan và có trách nhiệm!',
      },
    ],
  },
  {
    id: 'quiz-3',
    title: 'Biết nói lời cảm ơn và xin lỗi',
    description: 'Học cách cư xử văn minh, lễ phép với mọi người xung quanh.',
    category: 'giao_tiep',
    categoryLabel: 'Giao tiếp',
    ageRange: '4-6 tuổi',
    emoji: '🙏',
    questionCount: 4,
    reward_xp: 20,
    pass_score: 75,
    time_per_question: 30,
    difficulty: 'easy',
    questions: [
      {
        id: 'q3-1',
        question: 'Khi được người khác tặng quà hoặc giúp đỡ, bé cần nói gì?',
        options: [
          { id: 'opt-a', text: 'Cầm lấy và bỏ đi không nói gì' },
          { id: 'opt-b', text: 'Khoanh tay và mỉm cười nói: "Con cảm ơn ạ!"' },
          { id: 'opt-c', text: 'Chê quà không đẹp' },
          { id: 'opt-d', text: 'Bảo người khác tặng thêm quà nữa' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Lời cảm ơn chân thành thể hiện lòng biết ơn và sự lễ phép của bé.',
      },
      {
        id: 'q3-2',
        question: 'Nếu vô tình va phải bạn làm bạn ngã đau, bé nên làm gì?',
        options: [
          { id: 'opt-a', text: 'Cười to rồi chạy trốn' },
          { id: 'opt-b', text: 'Đổ lỗi cho bạn tự ngã' },
          { id: 'opt-c', text: 'Đỡ bạn dậy và nói: "Tớ xin lỗi bạn, bạn có sao không?"' },
          { id: 'opt-d', text: 'Đứng nhìn bạn khóc' },
        ],
        correct_answer: 'opt-c',
        explanation: 'Dũng cảm nhận lỗi và quan tâm bạn bè là hành động của một bé ngoan và biết thấu hiểu.',
      },
      {
        id: 'q3-3',
        question: 'Khi nhận bát cơm từ tay ông bà hoặc ba mẹ, thái độ của bé nên như thế nào?',
        options: [
          { id: 'opt-a', text: 'Đón bằng hai tay và nói lời mời cơm kính cẩn' },
          { id: 'opt-b', text: 'Giật lấy bằng một tay' },
          { id: 'opt-c', text: 'Cắm mặt vào điện thoại' },
          { id: 'opt-d', text: 'Gắt gỏng vì đói' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Nhận đồ bằng hai tay và lễ phép mời người lớn thể hiện nét đẹp văn hóa gia đình.',
      },
      {
        id: 'q3-4',
        question: 'Lời cảm ơn và xin lỗi nên được nói với giọng điệu như thế nào?',
        options: [
          { id: 'opt-a', text: 'Hét thật to làm mọi người giật mình' },
          { id: 'opt-b', text: 'Lẩm bẩm trong miệng không ai nghe thấy' },
          { id: 'opt-c', text: 'Chân thành, rõ ràng, mắt nhìn vào người đối diện' },
          { id: 'opt-d', text: 'Gắt gỏng khó chịu' },
        ],
        correct_answer: 'opt-c',
        explanation: 'Ánh mắt và nụ cười chân thành sẽ giúp lời nói chạm đến trái tim người nghe.',
      },
    ],
  },
  {
    id: 'quiz-4',
    title: 'Tô màu sáng tạo và thẩm mỹ',
    description: 'Khám phá thế giới màu sắc và rèn luyện sự khéo léo của đôi bàn tay.',
    category: 'sang_tao',
    categoryLabel: 'Sáng tạo',
    ageRange: '4-8 tuổi',
    emoji: '🎨',
    questionCount: 4,
    reward_xp: 35,
    pass_score: 75,
    time_per_question: 30,
    difficulty: 'medium',
    questions: [
      {
        id: 'q4-1',
        question: 'Để bức tranh không bị lem màu ra ngoài mép viền, bé nên tô như thế nào?',
        options: [
          { id: 'opt-a', text: 'Tô nhanh thật mạnh tay' },
          { id: 'opt-b', text: 'Viền nhẹ nhàng mép ngoài trước rồi tô dần vào bên trong' },
          { id: 'opt-c', text: 'Chấm bừa khắp mặt giấy' },
          { id: 'opt-d', text: 'Dùng bút chì gạch lung tung' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Viền nét ngoài trước là mẹo giúp bé giữ màu sắc nằm gọn gàng bên trong đường nét tranh.',
      },
      {
        id: 'q4-2',
        question: 'Khi pha màu Đỏ với màu Vàng, bé sẽ tạo ra màu sắc kì diệu nào?',
        options: [
          { id: 'opt-a', text: 'Màu Xanh lá' },
          { id: 'opt-b', text: 'Màu Cam ấm áp' },
          { id: 'opt-c', text: 'Màu Tím mộng mơ' },
          { id: 'opt-d', text: 'Màu Đen' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Màu Đỏ + Vàng = Màu Cam, giống màu của quả cam mọng nước và mặt trời hoàng hôn.',
      },
      {
        id: 'q4-3',
        question: 'Sau khi tô vẽ xong, bút màu và giấy vẽ nên được cất như thế nào?',
        options: [
          { id: 'opt-a', text: 'Cất gọn vào hộp bút và đậy nắp cẩn thận' },
          { id: 'opt-b', text: 'Vứt lăn lóc dưới sàn để người khác dọn' },
          { id: 'opt-c', text: 'Bẻ gãy hết bút sáp' },
          { id: 'opt-d', text: 'Vẽ bậy lên tường nhà' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Đậy nắp bút dạ và cất sáp màu vào hộp giúp bút không bị khô hay gãy, dùng được lâu hơn.',
      },
      {
        id: 'q4-4',
        question: 'Trong nghệ thuật hội họa, bé có được tự do phối màu theo trí tưởng tượng không?',
        options: [
          { id: 'opt-a', text: 'Hoàn toàn có! Trí tưởng tượng phong phú giúp bé sáng tạo nên điều kỳ diệu' },
          { id: 'opt-b', text: 'Không, phải vẽ y hệt người khác' },
          { id: 'opt-c', text: 'Chỉ được dùng 1 màu duy nhất' },
          { id: 'opt-d', text: 'Không bao giờ được sáng tạo' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Mỗi bạn nhỏ là một họa sĩ tài năng, hãy cứ thỏa sức sáng tạo thế giới theo góc nhìn của bé nhé!',
      },
    ],
  },
  {
    id: 'quiz-5',
    title: 'Rửa tay sạch khuẩn trước khi ăn',
    description: '6 bước rửa tay chuẩn khoa học giúp xua đuổi vi khuẩn gây bệnh.',
    category: 've_sinh',
    categoryLabel: 'Vệ sinh',
    ageRange: '4-6 tuổi',
    emoji: '🧼',
    questionCount: 4,
    reward_xp: 20,
    pass_score: 75,
    time_per_question: 30,
    difficulty: 'easy',
    questions: [
      {
        id: 'q5-1',
        question: 'Những thời điểm vàng nào bé nhất định phải rửa tay sạch bằng xà phòng?',
        options: [
          { id: 'opt-a', text: 'Chỉ khi nào thấy tay dính mực' },
          { id: 'opt-b', text: 'Trước khi ăn, sau khi đi vệ sinh, và sau khi chơi đùa ngoài sân' },
          { id: 'opt-c', text: 'Rửa tay trong lúc đang ngủ' },
          { id: 'opt-d', text: '1 ngày chỉ cần rửa 1 lần' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Vi khuẩn mắt thường không nhìn thấy được, hãy rửa tay xà phòng đều đặn để bảo vệ sức khỏe!',
      },
      {
        id: 'q5-2',
        question: 'Thời gian chà xát xà phòng tối thiểu trên bàn tay nên kéo dài bao lâu?',
        options: [
          { id: 'opt-a', text: 'Ít nhất 20 - 30 giây (hát trọn bài Happy Birthday)' },
          { id: 'opt-b', text: 'Nhúng nước 1 giây rồi nhấc ra ngay' },
          { id: 'opt-c', text: '1 tiếng đồng hồ' },
          { id: 'opt-d', text: '3 giây' },
        ],
        correct_answer: 'opt-a',
        explanation: '20-30 giây xà phòng mới kịp diệt sạch vi khuẩn bám ở kẽ móng tay và mu bàn tay.',
      },
      {
        id: 'q5-3',
        question: 'Sau khi xả sạch bọt xà phòng dưới vòi nước, bé làm khô tay bằng gì?',
        options: [
          { id: 'opt-a', text: 'Chùi đại vào vạt áo đang mặc' },
          { id: 'opt-b', text: 'Dùng khăn sạch riêng hoặc giấy lau tay sạch' },
          { id: 'opt-c', text: 'Lau vào sàn nhà' },
          { id: 'opt-d', text: 'Lau vào lông của bạn cún' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Khăn khô sạch hoặc khăn giấy giúp tay khô thoáng mà không bị nhiễm khuẩn trở lại.',
      },
      {
        id: 'q5-4',
        question: 'Tại sao chỉ nhúng tay vào nước không thì chưa đủ sạch vi khuẩn?',
        options: [
          { id: 'opt-a', text: 'Vì nước sạch quá' },
          { id: 'opt-b', text: 'Vì vi khuẩn có lớp mỡ bám dính, cần xà phòng tạo bọt mới cuốn trôi được' },
          { id: 'opt-c', text: 'Vì bàn tay không thích nước' },
          { id: 'opt-d', text: 'Nước làm tay bẩn hơn' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Xà phòng kết hợp nước chảy tạo nên siêu năng lực phá tan màng bọc của vi khuẩn gây bệnh!',
      },
    ],
  },
  {
    id: 'quiz-6',
    title: 'Chia sẻ đồ chơi và hòa đồng với bạn bè',
    description: 'Học cách đồng cảm, nhường nhịn và tạo nên tình bạn đẹp.',
    category: 'cam_xuc',
    categoryLabel: 'Cảm xúc',
    ageRange: '5-8 tuổi',
    emoji: '🤝',
    questionCount: 4,
    reward_xp: 30,
    pass_score: 75,
    time_per_question: 30,
    difficulty: 'medium',
    questions: [
      {
        id: 'q6-1',
        question: 'Khi bạn đến nhà chơi và muốn mượn món đồ chơi bé thích, bé nên làm gì?',
        options: [
          { id: 'opt-a', text: 'Giấu đồ chơi đi và quát mắng bạn' },
          { id: 'opt-b', text: 'Rủ bạn cùng chơi chung hoặc thỏa thuận luân phiên nhau chơi' },
          { id: 'opt-c', text: 'Đánh bạn để đuổi bạn về' },
          { id: 'opt-d', text: 'Đập vỡ đồ chơi' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Cùng chơi chung sẽ vui hơn gấp đôi và giúp bé xây dựng tình bạn gắn bó!',
      },
      {
        id: 'q6-2',
        question: 'Khi thấy bạn trong lớp ngồi một mình buồn bã, bé có thể làm gì?',
        options: [
          { id: 'opt-a', text: 'Đến gần hỏi thăm và rủ bạn cùng tham gia trò chơi' },
          { id: 'opt-b', text: 'Chỉ tay trêu chọc bạn' },
          { id: 'opt-c', text: 'Bỏ mặc không quan tâm' },
          { id: 'opt-d', text: 'Nói xấu bạn với người khác' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Sự quan tâm chân thành và nụ cười ấm áp của bé sẽ giúp bạn xua tan nỗi buồn.',
      },
      {
        id: 'q6-3',
        question: 'Nếu hai bạn cùng muốn chơi một chiếc xích đu ở sân trường, cách giải quyết tốt nhất là?',
        options: [
          { id: 'opt-a', text: 'Xô đẩy bạn để giành giật' },
          { id: 'opt-b', text: 'Đếm số nhịp đu (mỗi bạn 20 lượt) rồi đổi phiên nhau vui vẻ' },
          { id: 'opt-c', text: 'Ngồi chiếm xích đu cả ngày' },
          { id: 'opt-d', text: 'Khóc to để cô giáo mắng bạn' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Xếp hàng và chờ đến lượt là quy tắc vàng của sự văn minh khi chơi ở nơi công cộng.',
      },
      {
        id: 'q6-4',
        question: 'Biết chia sẻ niềm vui và đồ chơi mang lại cảm xúc gì cho chính bé?',
        options: [
          { id: 'opt-a', text: 'Cảm thấy mất mát và bực bội' },
          { id: 'opt-b', text: 'Cảm thấy vui sướng, hạnh phúc và được mọi người yêu quý' },
          { id: 'opt-c', text: 'Cảm thấy sợ hãi' },
          { id: 'opt-d', text: 'Không có cảm xúc gì' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Cho đi là nhận lại nụ cười và niềm hạnh phúc ngọt ngào nhất!',
      },
    ],
    status: 'visible',
  },
  {
    id: 'quiz-7',
    title: 'Tự chuẩn bị cặp sách đi học',
    description: 'Bé học cách sắp xếp sách vở, đồ dùng học tập theo thời khóa biểu.',
    category: 'tu_lap',
    categoryLabel: 'Tự lập',
    ageRange: '6-8 tuổi',
    ageMin: 6,
    ageMax: 8,
    emoji: '📚',
    questionCount: 4,
    reward_xp: 20,
    pass_score: 75,
    time_per_question: 30,
    difficulty: 'easy',
    status: 'visible',
    questions: [
      {
        id: 'q7-1',
        question: 'Thời điểm nào tốt nhất để bé chuẩn bị cặp sách đi học ngày mai?',
        options: [
          { id: 'opt-a', text: 'Buổi tối trước khi đi ngủ' },
          { id: 'opt-b', text: 'Sáng mai chuẩn bị đi học mới cuống cuồng soạn' },
          { id: 'opt-c', text: 'Đến lớp mới mượn sách của bạn' },
          { id: 'opt-d', text: 'Không cần mang sách vở' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Chuẩn bị từ tối hôm trước giúp bé không bị quên sách vở và sáng dậy thảnh thơi hơn.',
      },
      {
        id: 'q7-2',
        question: 'Để mang đúng sách vở cho các tiết học, bé cần xem cái gì?',
        options: [
          { id: 'opt-a', text: 'Xem phim hoạt hình' },
          { id: 'opt-b', text: 'Xem thời khóa biểu dán ở góc học tập' },
          { id: 'opt-c', text: 'Đoán bừa' },
          { id: 'opt-d', text: 'Nhét hết cả tủ sách vào cặp' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Thời khóa biểu ghi rõ các môn học trong ngày để bé chọn đúng sách vở cần thiết.',
      },
      {
        id: 'q7-3',
        question: 'Đồ dùng học tập như bút chì, thước kẻ, tẩy nên để ở đâu trong cặp?',
        options: [
          { id: 'opt-a', text: 'Ném lung tung dưới đáy cặp' },
          { id: 'opt-b', text: 'Cất gọn gàng vào hộp bút riêng' },
          { id: 'opt-c', text: 'Bỏ vào túi áo khoác' },
          { id: 'opt-d', text: 'Để ở nhà' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Hộp bút giúp bảo quản ngòi bút chì không bị gãy và lấy ra dùng rất nhanh.',
      },
      {
        id: 'q7-4',
        question: 'Những thứ nào KHÔNG NÊN mang vào cặp sách khi đi học?',
        options: [
          { id: 'opt-a', text: 'Vở bài tập' },
          { id: 'opt-b', text: 'Đồ chơi cồng kềnh, vật sắc nhọn nguy hiểm' },
          { id: 'opt-c', text: 'Hộp bút chì màu' },
          { id: 'opt-d', text: 'Bình nước uống cá nhân' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Đồ chơi dễ làm bé xao nhãng trong giờ học, và đồ sắc nhọn có thể gây nguy hiểm cho bé và bạn bè.',
      },
    ],
  },
  {
    id: 'quiz-8',
    title: 'Chào hỏi lễ phép với mọi người',
    description: 'Học văn hóa giao tiếp lễ phép, kính trên nhường dưới trong gia đình và trường lớp.',
    category: 'le_phep',
    categoryLabel: 'Lễ phép',
    ageRange: '4-7 tuổi',
    ageMin: 4,
    ageMax: 7,
    emoji: '😊',
    questionCount: 3,
    reward_xp: 15,
    pass_score: 66,
    time_per_question: 30,
    difficulty: 'easy',
    status: 'visible',
    questions: [
      {
        id: 'q8-1',
        question: 'Tư thế chào hỏi lễ phép chuẩn của một bé ngoan là thế nào?',
        options: [
          { id: 'opt-a', text: 'Vừa chạy vừa hét lớn' },
          { id: 'opt-b', text: 'Đứng ngay ngắn, vòng hai tay trước ngực và hơi cúi đầu' },
          { id: 'opt-c', text: 'Khoanh tay nhưng liếc mắt nhìn chỗ khác' },
          { id: 'opt-d', text: 'Đút tay vào túi quần' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Vòng tay trước ngực và cúi đầu thể hiện sự tôn trọng chân thành với người lớn tuổi.',
      },
      {
        id: 'q8-2',
        question: 'Khi đi học về đến nhà, câu đầu tiên bé nên nói là gì?',
        options: [
          { id: 'opt-a', text: 'Bật tivi cho con xem!' },
          { id: 'opt-b', text: 'Con chào ông bà, con chào bố mẹ con mới đi học về ạ!' },
          { id: 'opt-c', text: 'Vứt cặp và chạy vào phòng' },
          { id: 'opt-d', text: 'Đói bụng quá cho ăn đi!' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Lời chào ấm áp làm tan biến mọi mệt mỏi của ông bà, cha mẹ sau một ngày làm việc.',
      },
      {
        id: 'q8-3',
        question: 'Khi khách đến chơi nhà, bé cần thể hiện thái độ ra sao?',
        options: [
          { id: 'opt-a', text: 'Lễ phép chào hỏi, mời khách ngồi và rót nước mời khách' },
          { id: 'opt-b', text: 'Trốn biệt trong phòng không chào' },
          { id: 'opt-c', text: 'Chạy nhảy la hét ầm ĩ trước mặt khách' },
          { id: 'opt-d', text: 'Đòi khách cho tiền' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Chào khách niềm nở thể hiện sự hiếu khách và gia giáo tốt của bé.',
      },
    ],
  },
  {
    id: 'quiz-9',
    title: 'Thói quen ngủ sớm và đúng giờ',
    description: 'Tầm quan trọng của giấc ngủ đủ giấc đối với sự phát triển chiều cao và trí não.',
    category: 'suc_khoe',
    categoryLabel: 'Sức khỏe',
    ageRange: '4-8 tuổi',
    ageMin: 4,
    ageMax: 8,
    emoji: '🌙',
    questionCount: 4,
    reward_xp: 25,
    pass_score: 75,
    time_per_question: 30,
    difficulty: 'medium',
    status: 'hidden', // Bộ đề mẫu ở trạng thái ẨN để test filter Admin
    questions: [
      {
        id: 'q9-1',
        question: 'Bé ở lứa tuổi mầm non và tiểu học nên đi ngủ vào thời gian nào buổi tối?',
        options: [
          { id: 'opt-a', text: 'Khoảng 21h00 - 21h30 (không thức quá 22h)' },
          { id: 'opt-b', text: '1h sáng hôm sau' },
          { id: 'opt-c', text: 'Thức trắng đêm chơi game' },
          { id: 'opt-d', text: '18h tối ngủ luôn đến sáng' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Khung giờ vàng từ 22h đêm đến 2h sáng là lúc cơ thể tiết ra nhiều hormone tăng trưởng chiều cao nhất.',
      },
      {
        id: 'q9-2',
        question: 'Trước khi lên giường đi ngủ 30 phút, bé KHÔNG NÊN làm việc gì?',
        options: [
          { id: 'opt-a', text: 'Nghe kể chuyện cổ tích dịu dàng' },
          { id: 'opt-b', text: 'Xem điện thoại, ipad hoặc tivi' },
          { id: 'opt-c', text: 'Đánh răng rửa mặt sạch sẽ' },
          { id: 'opt-d', text: 'Mặc đồ ngủ thoải mái' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Ánh sáng xanh từ màn hình thiết bị điện tử làm não bộ tỉnh táo, khó đi vào giấc ngủ sâu.',
      },
      {
        id: 'q9-3',
        question: 'Mỗi đêm bé cần ngủ đủ khoảng bao nhiêu tiếng để sáng mai tràn đầy năng lượng?',
        options: [
          { id: 'opt-a', text: '3 tiếng' },
          { id: 'opt-b', text: '9 đến 11 tiếng' },
          { id: 'opt-c', text: '20 tiếng' },
          { id: 'opt-d', text: '1 tiếng' },
        ],
        correct_answer: 'opt-b',
        explanation: '9-11 tiếng ngủ ngon giúp cơ thể nghỉ ngơi, não bộ lưu trữ kiến thức và bé lớn nhanh như thổi!',
      },
      {
        id: 'q9-4',
        question: 'Thức khuya thường xuyên sẽ gây ra hậu quả xấu gì cho cơ thể?',
        options: [
          { id: 'opt-a', text: 'Giúp thông minh và cao lớn hơn' },
          { id: 'opt-b', text: 'Mệt mỏi, mắt thâm quầng, giảm trí nhớ và chậm lớn' },
          { id: 'opt-c', text: 'Không bị ảnh hưởng gì' },
          { id: 'opt-d', text: 'Tất cả đều sai' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Ngủ sớm dậy sớm là thói quen vàng của các nhà vô địch và siêu nhân nhí!',
      },
    ],
  },
  {
    id: 'quiz-10',
    title: 'Uống đủ nước mỗi ngày',
    description: 'Nước là nguồn sống diệu kỳ giúp thanh lọc cơ thể và tăng sức đề kháng.',
    category: 'suc_khoe',
    categoryLabel: 'Sức khỏe',
    ageRange: '4-8 tuổi',
    ageMin: 4,
    ageMax: 8,
    emoji: '💧',
    questionCount: 3,
    reward_xp: 20,
    pass_score: 66,
    time_per_question: 30,
    difficulty: 'easy',
    status: 'visible',
    questions: [
      {
        id: 'q10-1',
        question: 'Loại nước nào tốt nhất và an toàn nhất cho cơ thể bé hàng ngày?',
        options: [
          { id: 'opt-a', text: 'Nước lọc / nước đun sôi để nguội' },
          { id: 'opt-b', text: 'Nước ngọt có gas nhiều đường' },
          { id: 'opt-c', text: 'Trà sữa trân châu' },
          { id: 'opt-d', text: 'Nước bẩn ngoài mương' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Nước lọc tinh khiết thanh lọc cơ thể mà không gây sâu răng hay béo phì như nước ngọt có gas.',
      },
      {
        id: 'q10-2',
        question: 'Bé nên uống nước như thế nào trong ngày?',
        options: [
          { id: 'opt-a', text: 'Đợi đến khi khát khô cổ họng mới uống' },
          { id: 'opt-b', text: 'Uống từng ngụm nhỏ rải rác trong suốt cả ngày' },
          { id: 'opt-c', text: 'Uống một hơi hết cả xô nước' },
          { id: 'opt-d', text: 'Không uống nước mà chỉ ăn kẹo' },
        ],
        correct_answer: 'opt-b',
        explanation: 'Uống từng ngụm nhỏ đều đặn giúp tế bào trong cơ thể hấp thu nước hiệu quả nhất.',
      },
      {
        id: 'q10-3',
        question: 'Dấu hiệu nào cho thấy cơ thể bé đang bị thiếu nước cần bổ sung ngay?',
        options: [
          { id: 'opt-a', text: 'Môi khô, nước tiểu có màu vàng sậm, người mệt mỏi' },
          { id: 'opt-b', text: 'Môi hồng hào bóng bẩy' },
          { id: 'opt-c', text: 'Cảm thấy rất sảng khoái' },
          { id: 'opt-d', text: 'Tất cả đều sai' },
        ],
        correct_answer: 'opt-a',
        explanation: 'Khi thấy môi khô nứt nẻ và thấy khát, hãy lấy ngay một ly nước mát uống nhé bé!',
      },
    ],
  },
];
