// Mock data cho module "Học Bài Video"
// TODO: Replace with API call → GET /api/videos?category=...
import { VideoLesson } from '@/shared/types/videoLesson';

export const INITIAL_VIDEO_LESSONS: VideoLesson[] = [
  {
    id: 'vid-1',
    title: 'Cách đánh răng đúng cách',
    description: 'Cùng Cô Hoa làm quen với bạn Bàn Chải Xinh và học cách chải răng 2 phút sáng tối để hàm răng luôn trắng sáng tinh tươm nhé!',
    category: 've_sinh',
    categoryLabel: 'Vệ sinh',
    ageMin: 4,
    ageMax: 6,
    ageLabel: '4-6 tuổi',
    duration: '5:00',
    durationSeconds: 300,
    thumbnail_emoji: '🦷',
    thumbnail_color: '#E0F2FE', // pastel sky blue
    video_url: 'https://www.youtube.com/watch?v=wxM6kePuv2Y', // Sample YouTube URL
    instructor: 'Cô Hoa',
    reward_xp: 15,
    views: 1250,
    tags: ['Vệ sinh', 'Răng miệng', 'Kỹ năng cơ bản'],
    status: 'visible',
    keyTakeaways: [
      'Đánh răng ít nhất 2 lần mỗi ngày: Sáng sau khi thức dậy và Tối trước khi ngủ',
      'Đánh răng theo chiều vòng tròn hoặc dọc, kéo dài đủ 2 phút',
      'Nhớ làm sạch cả mặt trong, mặt ngoài và mặt nhai của răng',
      'Súc miệng kỹ bằng nước sạch và nhổ hết bọt kem đánh răng',
    ],
  },
  {
    id: 'vid-2',
    title: 'Tự gấp quần áo gọn gàng',
    description: 'Thầy Nam hướng dẫn bí quyết gấp áo phông, gấp quần soóc siêu tốc và xếp ngăn nắp vào tủ đồ cá nhân.',
    category: 'tu_lap',
    categoryLabel: 'Tự lập',
    ageMin: 6,
    ageMax: 8,
    ageLabel: '6-8 tuổi',
    duration: '7:00',
    durationSeconds: 420,
    thumbnail_emoji: '👕',
    thumbnail_color: '#F3E8FF', // pastel purple
    video_url: 'https://www.youtube.com/watch?v=36YnV9STBqc', // Sample YouTube URL
    instructor: 'Thầy Nam',
    reward_xp: 20,
    views: 980,
    tags: ['Tự lập', 'Sắp xếp', 'Việc nhà'],
    status: 'visible',
    keyTakeaways: [
      'Trải áo quần phẳng phiu trên mặt phẳng sạch sẽ trước khi gấp',
      'Gấp hai bên tay áo vào trong mép giữa để tạo thành hình chữ nhật',
      'Gấp đôi từ gấu áo lên cổ áo và vuốt phẳng nếp gấp',
      'Phân loại áo thun, quần dài và cất vào đúng ngăn tủ riêng',
    ],
  },
  {
    id: 'vid-3',
    title: 'Biết nói lời cảm ơn và xin lỗi',
    description: 'Khám phá hai "câu thần chú nhiệm màu" giúp bé luôn nhận được sự yêu thương và nụ cười từ tất cả mọi người.',
    category: 'giao_tiep',
    categoryLabel: 'Giao tiếp',
    ageMin: 4,
    ageMax: 6,
    ageLabel: '4-6 tuổi',
    duration: '4:00',
    durationSeconds: 240,
    thumbnail_emoji: '🙏',
    thumbnail_color: '#FEF3C7', // pastel warm yellow
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', // Direct MP4
    instructor: 'Cô Mai',
    reward_xp: 15,
    views: 2100,
    tags: ['Giao tiếp', 'Lễ phép', 'Ứng xử'],
    status: 'visible',
    keyTakeaways: [
      'Khoanh tay và mỉm cười khi nói lời "Cảm ơn" khi được giúp đỡ hoặc nhận quà',
      'Dũng cảm nói lời "Xin lỗi" chân thành khi vô tình làm ai đó tổn thương hay buồn phiền',
      'Mắt nhìn vào người đối diện và nói rõ ràng, dịu dàng',
      'Lời nói tử tế mang lại niềm vui cho cả người nghe và bản thân bé',
    ],
  },
  {
    id: 'vid-4',
    title: 'Tô màu sáng tạo cùng sắc cầu vồng',
    description: 'Bước vào thế giới sắc màu kỳ ảo cùng Cô Lan, tìm hiểu vòng tròn màu sắc và mẹo tô tranh không bị lem ra ngoài.',
    category: 'sang_tao',
    categoryLabel: 'Sáng tạo',
    ageMin: 4,
    ageMax: 8,
    ageLabel: '4-8 tuổi',
    duration: '10:00',
    durationSeconds: 600,
    thumbnail_emoji: '🎨',
    thumbnail_color: '#FCE7F3', // pastel pink
    video_url: 'https://www.youtube.com/watch?v=wxM6kePuv2Y',
    instructor: 'Cô Lan',
    reward_xp: 25,
    views: 750,
    tags: ['Sáng tạo', 'Hội họa', 'Màu sắc'],
    status: 'visible',
    keyTakeaways: [
      'Viền nhẹ viền ngoài của hình vẽ trước khi tô đều màu vào bên trong',
      'Khám phá pha màu diệu kỳ: Đỏ + Vàng ra Cam, Xanh dương + Vàng ra Xanh lá',
      'Cầm bút nghiêng vừa phải và tô theo một chiều nhất định',
      'Đậy nắp bút hoặc xếp gọn sáp màu vào hộp sau khi hoàn thành tác phẩm',
    ],
  },
  {
    id: 'vid-5',
    title: 'Rửa tay sạch khuẩn trước khi ăn',
    description: 'Bác sĩ Tùng biểu diễn 6 bước rửa tay tiêu chuẩn của Bộ Y tế theo điệu nhảy âm nhạc sôi động.',
    category: 've_sinh',
    categoryLabel: 'Vệ sinh',
    ageMin: 4,
    ageMax: 6,
    ageLabel: '4-6 tuổi',
    duration: '3:00',
    durationSeconds: 180,
    thumbnail_emoji: '🧼',
    thumbnail_color: '#DCFCE7', // pastel green
    video_url: 'https://www.youtube.com/watch?v=36YnV9STBqc',
    instructor: 'Bác sĩ Tùng',
    reward_xp: 10,
    views: 3200,
    tags: ['Vệ sinh', 'Sức khỏe', 'Rửa tay'],
    status: 'visible',
    keyTakeaways: [
      'Làm ướt tay, lấy lượng xà phòng vừa đủ và chà xát tạo bọt bông tuyết',
      'Chà sạch kẽ ngón tay, mu bàn tay và đầu ngón tay trong tối thiểu 20-30 giây',
      'Xả sạch dưới vòi nước chảy để cuốn trôi toàn bộ mầm bệnh',
      'Lau khô bằng khăn sạch hoặc giấy mềm',
    ],
  },
  {
    id: 'vid-6',
    title: 'Chia sẻ đồ chơi với bạn bè',
    description: 'Câu chuyện cảm động về Chú gấu Bơ và bài học tuyệt vời khi biết sẻ chia niềm vui cùng những người bạn thân thương.',
    category: 'cam_xuc',
    categoryLabel: 'Cảm xúc',
    ageMin: 5,
    ageMax: 8,
    ageLabel: '5-8 tuổi',
    duration: '6:00',
    durationSeconds: 360,
    thumbnail_emoji: '🤝',
    thumbnail_color: '#FFE4E6', // pastel rose
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    instructor: 'Cô Hạnh',
    reward_xp: 20,
    views: 1500,
    tags: ['Cảm xúc', 'Tình bạn', 'Chia sẻ'],
    status: 'visible',
    keyTakeaways: [
      'Cùng chơi chung sẽ nhân đôi tiếng cười và tạo nên kỷ niệm đẹp',
      'Thỏa thuận đổi lượt chơi công bằng khi cùng thích một món đồ chơi',
      'Lắng nghe và tôn trọng sở thích của bạn bè',
      'Biết giữ gìn đồ chơi của bạn cẩn thận khi được mượn',
    ],
  },
  {
    id: 'vid-7',
    title: 'Tự chuẩn bị cặp sách đi học',
    description: 'Bé lớn rồi tự lập thôi! Cùng Thầy Nam xem thời khóa biểu, xếp sách vở và đồ dùng học tập trước khi đi ngủ nhé.',
    category: 'tu_lap',
    categoryLabel: 'Tự lập',
    ageMin: 6,
    ageMax: 8,
    ageLabel: '6-8 tuổi',
    duration: '5:00',
    durationSeconds: 300,
    thumbnail_emoji: '📚',
    thumbnail_color: '#E0E7FF', // pastel indigo
    video_url: 'https://www.youtube.com/watch?v=wxM6kePuv2Y',
    instructor: 'Thầy Nam',
    reward_xp: 20,
    views: 890,
    tags: ['Tự lập', 'Học tập', 'Cặp sách'],
    status: 'hidden', // Video đang ẩn theo yêu cầu thiết kế
    keyTakeaways: [
      'Soi kỹ thời khóa biểu ngày mai để chọn đúng sách giáo khoa và vở bài tập',
      'Gọt sẵn bút chì, chuẩn bị tẩy, thước kẻ và hộp bút gọn gàng',
      'Không mang theo đồ chơi hoặc đồ vật nguy hiểm đến trường',
      'Kéo khóa cặp cẩn thận và để ở góc bàn học sẵn sàng cho sáng mai',
    ],
  },
  {
    id: 'vid-8',
    title: 'Chào hỏi lễ phép với người lớn',
    description: 'Học cách vòng tay, cúi đầu chào ông bà, cha mẹ, thầy cô và khách đến chơi nhà để luôn là em bé ngoan đáng yêu.',
    category: 'le_phep',
    categoryLabel: 'Lễ phép',
    ageMin: 4,
    ageMax: 7,
    ageLabel: '4-7 tuổi',
    duration: '4:00',
    durationSeconds: 240,
    thumbnail_emoji: '😊',
    thumbnail_color: '#CCFBF1', // pastel teal
    video_url: 'https://www.youtube.com/watch?v=36YnV9STBqc',
    instructor: 'Cô Mai',
    reward_xp: 15,
    views: 1780,
    tags: ['Lễ phép', 'Gia đình', 'Chào hỏi'],
    status: 'hidden', // Video đang ẩn theo yêu cầu thiết kế
    keyTakeaways: [
      'Khi gặp người lớn, đứng ngay ngắn, vòng hai tay trước ngực và cúi đầu chào',
      'Nói to, rõ ràng và lễ phép: "Con chào ông/bà/bố/mẹ ạ!"',
      'Chào hỏi khi đi học về, khi có khách đến thăm nhà và khi tạm biệt',
      'Nụ cười và thái độ niềm nở là điểm cộng siêu đáng yêu của bé',
    ],
  },
];
