import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { kidlifeColors as C, kidlifeLayout as L } from '@/theme';
import ReportsParentScreen from './ReportsParentScreen';
import RewardsParentScreen from './RewardsParentScreen';
import PremiumScreen from './PremiumScreen';

type Subscreen = 'account' | 'reports' | 'rewards' | 'premium';
export default function AccountParentScreen() {
  const [subscreen, setSubscreen] = useState<Subscreen>('account');
  if (subscreen === 'reports') return <View style={styles.subscreen}><Pressable style={styles.back} onPress={() => setSubscreen('account')}><Ionicons name="chevron-back" size={20} color={C.primary} /><Text style={styles.backText}>Tài khoản</Text></Pressable><ReportsParentScreen /></View>;
  if (subscreen === 'rewards') return <View style={styles.subscreen}><Pressable style={styles.back} onPress={() => setSubscreen('account')}><Ionicons name="chevron-back" size={20} color={C.primary} /><Text style={styles.backText}>Tài khoản</Text></Pressable><RewardsParentScreen /></View>;
  if (subscreen === 'premium') return <View style={styles.subscreen}><Pressable style={styles.back} onPress={() => setSubscreen('account')}><Ionicons name="chevron-back" size={20} color={C.primary} /><Text style={styles.backText}>Tài khoản</Text></Pressable><PremiumScreen /></View>;
  return <ScrollView style={L.screen} contentContainerStyle={L.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Text style={styles.title}>Tài khoản</Text><Pressable><Ionicons name="settings-outline" size={22} color={C.primary} /></Pressable></View><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>👩🏻</Text></View><View style={styles.profileCopy}><Text style={styles.name}>Nguyễn Thị Nga</Text><Text style={styles.email}>nguyennga@email.com</Text><View style={styles.editPill}><Ionicons name="pencil" size={11} color={C.primary} /><Text style={styles.editText}>Chỉnh sửa</Text></View></View></View><View style={styles.childTitle}><Text style={L.sectionTitle}>Tài khoản con</Text><Pressable><Text style={styles.add}>+ Thêm bé</Text></Pressable></View><View style={[L.card, styles.childCard]}><View style={styles.childAvatar}><Text style={styles.childEmoji}>🧒🏻</Text></View><View style={styles.childCopy}><Text style={styles.childName}>Bé Minh Anh</Text><Text style={styles.childMeta}>5 tuổi  •  Cấp 5  •  1,250 XP</Text></View><Ionicons name="chevron-forward" size={20} color={C.primary} /></View><View style={styles.menu}>{[['💳', 'Gói KidLife Premium', 'Đang hoạt động', 'premium'], ['📈', 'Báo cáo tiến độ', 'Xem tiến bộ của bé', 'reports'], ['🎁', 'Phần thưởng & ví', 'Quản lý phần thưởng', 'rewards'], ['🔔', 'Thông báo', '', ''], ['❓', 'Trợ giúp & hỗ trợ', '', '']].map(([icon, label, detail, target]) => <Pressable style={styles.menuItem} key={label} onPress={() => target && setSubscreen(target as Subscreen)}><Text style={styles.menuIcon}>{icon}</Text><View style={styles.menuCopy}><Text style={styles.menuLabel}>{label}</Text>{detail && <Text style={styles.menuDetail}>{detail}</Text>}</View>{label === 'Gói KidLife Premium' && <View style={styles.active}><Text style={styles.activeText}>Premium</Text></View>}<Ionicons name="chevron-forward" size={18} color={C.muted} /></Pressable>)}</View><Pressable style={styles.logout}><Ionicons name="log-out-outline" size={19} color={C.red} /><Text style={styles.logoutText}>Đăng xuất</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ subscreen: { flex: 1, backgroundColor: C.background }, back: { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 20, paddingTop: 8, paddingBottom: 5 }, backText: { color: C.primary, fontSize: 12, fontWeight: '800' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 8, marginBottom: 20 }, title: { color: C.text, fontSize: 28, fontWeight: '800' }, profile: { ...L.card, padding: 16, flexDirection: 'row', alignItems: 'center', marginBottom: 24 }, avatar: { width: 70, height: 70, borderRadius: 24, backgroundColor: C.primarySoft, alignItems: 'center', justifyContent: 'center', marginRight: 13 }, avatarText: { fontSize: 38 }, profileCopy: { flex: 1 }, name: { color: C.text, fontSize: 16, fontWeight: '800' }, email: { color: C.muted, fontSize: 11, marginTop: 4 }, editPill: { flexDirection: 'row', gap: 4, alignItems: 'center', backgroundColor: C.primarySoft, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5, alignSelf: 'flex-start', marginTop: 8 }, editText: { color: C.primary, fontSize: 10, fontWeight: '700' }, childTitle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, add: { color: C.primary, fontSize: 11, fontWeight: '800' }, childCard: { padding: 13, flexDirection: 'row', alignItems: 'center', marginBottom: 25 }, childAvatar: { width: 48, height: 48, borderRadius: 15, backgroundColor: C.orangeSoft, alignItems: 'center', justifyContent: 'center', marginRight: 11 }, childEmoji: { fontSize: 27 }, childCopy: { flex: 1 }, childName: { color: C.text, fontSize: 13, fontWeight: '800' }, childMeta: { color: C.muted, fontSize: 10, marginTop: 4 }, menu: { ...L.card, paddingHorizontal: 14 }, menuItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: C.border }, menuIcon: { fontSize: 20, marginRight: 11 }, menuCopy: { flex: 1 }, menuLabel: { color: C.text, fontSize: 12, fontWeight: '700' }, menuDetail: { color: C.green, fontSize: 10, marginTop: 3 }, active: { backgroundColor: C.lime, paddingHorizontal: 7, paddingVertical: 4, borderRadius: 5, marginRight: 8 }, activeText: { color: C.limeDark, fontSize: 9, fontWeight: '900' }, logout: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, marginTop: 22, paddingVertical: 13 }, logoutText: { color: C.red, fontSize: 12, fontWeight: '800' } });
