import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const COLORS = {
  primary: '#2B44E8',
  primaryDark: '#1A298C',
  background: '#F4F6FB',
  white: '#FFFFFF',
  textDark: '#1B205D',
  textLight: '#8B95B7',
  textGray: '#A0A7C0',
  taskCompleted: '#C9ED3A',
  taskPending: '#E8EDFC',
  messageBg: '#EAF4D0',
  messageText: '#4F7009',
  green: '#96D14B',
  red: '#FF6B6B',
  orange: '#FFA900',
  purple: '#8E54E9',
  grayBg: '#F3F4F8',
  overlay: 'rgba(0, 0, 0, 0.5)',
  yellow: '#FFD233',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 40 : 10,
    paddingBottom: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#E8EDFC',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarEmoji: {
    fontSize: 24,
  },
  headerTitles: {
    justifyContent: 'center',
  },
  greetingText: {
    fontSize: 14,
    color: COLORS.textDark,
    marginBottom: 4,
  },
  childNameSelector: {
    paddingVertical: 2,
  },
  childName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.primaryDark,
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E8EDFC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overviewCard: {
    backgroundColor: COLORS.primary,
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
  },
  xpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  xpLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  xpText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 14,
  },
  levelText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 12,
  },
  progressBarContainer: {
    height: 10,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 5,
    marginBottom: 20,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: COLORS.taskCompleted,
    borderRadius: 5,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statBox: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  statNumber: {
    color: COLORS.white,
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 8,
    marginBottom: 4,
  },
  statLabel: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 11,
    textAlign: 'center',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 8,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginLeft: 8,
  },
  streakBadge: {
    backgroundColor: '#FFF0D4',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  streakBadgeText: {
    color: '#E55934',
    fontWeight: 'bold',
    fontSize: 12,
  },
  streakCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
  },
  daysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dayCol: {
    alignItems: 'center',
  },
  dayText: {
    fontSize: 12,
    color: COLORS.textLight,
    marginBottom: 8,
  },
  dayCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayCircleActive: {
    backgroundColor: '#FF6B6B',
  },
  dayCircleInactive: {
    backgroundColor: COLORS.grayBg,
  },
  dotInactive: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.textLight,
  },
  todayDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#10B981',
    marginTop: 6,
  },
  streakMessage: {
    textAlign: 'center',
    color: COLORS.textLight,
    fontSize: 14,
  },
  taskBadge: {
    backgroundColor: '#EAF0FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  taskBadgeText: {
    color: COLORS.primary,
    fontWeight: 'bold',
    fontSize: 12,
  },
  parentMessageCard: {
    backgroundColor: COLORS.messageBg,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  parentMessageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  parentMessageIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  parentMessageTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  parentMessageContent: {
    fontSize: 14,
    color: COLORS.messageText,
    lineHeight: 20,
  },
  taskList: {
    marginBottom: 24,
  },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
  },
  taskIconContainer: {
    width: 50,
    height: 50,
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  taskEmoji: {
    fontSize: 28,
  },
  taskInfo: {
    flex: 1,
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 8,
  },
  taskRewards: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rewardStar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
  },
  rewardStarText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginLeft: 4,
  },
  rewardXp: {
    backgroundColor: 'rgba(224, 187, 255, 0.3)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  rewardXpText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: COLORS.purple,
  },
  taskArrowBtn: {
    width: 40,
    height: 40,
    backgroundColor: COLORS.white,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
  },
  progressContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  circularProgressContainer: {
    width: 100,
    height: 100,
    marginRight: 20,
  },
  circularProgressBase: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: COLORS.grayBg,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  circularProgressActive: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 10,
    borderColor: COLORS.primary,
    borderLeftColor: 'transparent',
    borderBottomColor: 'transparent',
    transform: [{ rotate: '-45deg' }],
  },
  circularProgressInner: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  circularProgressPercent: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.primaryDark,
  },
  circularProgressLabel: {
    fontSize: 10,
    color: COLORS.textLight,
  },
  barChartsContainer: {
    flex: 1,
  },
  barChartRow: {
    marginBottom: 8,
  },
  barChartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  barChartLabel: {
    fontSize: 12,
    color: COLORS.textDark,
    fontWeight: '600',
  },
  barChartValue: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  barTrack: {
    height: 6,
    backgroundColor: COLORS.grayBg,
    borderRadius: 3,
  },
  barFill: {
    height: '100%',
    borderRadius: 3,
  },
  trophyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F8',
    padding: 16,
    borderRadius: 16,
  },
  trophyBannerTextContainer: {
    marginLeft: 12,
    flex: 1,
  },
  trophyBannerTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 2,
  },
  trophyBannerSub: {
    fontSize: 12,
    color: COLORS.textLight,
  },
  badgeScrollView: {
    marginBottom: 24,
  },
  badgeScrollContent: {
    paddingRight: 20,
  },
  badgeItem: {
    alignItems: 'center',
    marginRight: 16,
  },
  badgeIconBox: {
    width: 70,
    height: 70,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  lockedBadge: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lockIconOverlay: {
    position: 'absolute',
    bottom: -5,
    right: -5,
    backgroundColor: COLORS.white,
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeName: {
    fontSize: 12,
    color: COLORS.textLight,
    fontWeight: '500',
  },
  bottomPadding: {
    height: 100, // padding for absolute bottom tab bar
  },
  bottomTabBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: Platform.OS === 'ios' ? 90 : 70,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: Platform.OS === 'ios' ? 20 : 0,
    borderTopWidth: 1,
    borderTopColor: '#E8EDFC',
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  tabItemActiveBg: {
    backgroundColor: '#EAF0FF',
    width: 48,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  tabText: {
    fontSize: 10,
    color: COLORS.textLight,
    marginTop: 4,
  },
  tabTextActive: {
    color: COLORS.primary,
    fontWeight: 'bold',
    marginTop: 0,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: 'flex-start',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    marginTop: Platform.OS === 'ios' ? 100 : 80,
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 14,
    color: COLORS.primaryDark,
    marginBottom: 16,
  },
  modalChildItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  modalChildItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#F0F2F8',
  },
  modalAvatarContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E8EDFC',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  modalAvatarEmoji: {
    fontSize: 20,
  },
  modalChildName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primaryDark,
  },
});
