import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, View, Text } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { kidlifeColors as C, kidlifeLayout as L } from '@/theme';

const skills = [{ name: 'Giao tiếp', value: 72, color: C.purple }, { name: 'Tự lập', value: 55, color: C.green }, { name: 'Cảm xúc', value: 88, color: C.red }, { name: 'Sáng tạo', value: 40, color: C.orange }];
export default function ReportsParentScreen() {
  const [range, setRange] = useState('Tuần này');
  return <ScrollView style={L.screen} contentContainerStyle={L.content} showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text style={styles.overline}>THEO DÕI TIẾN ĐỘ</Text><Text style={styles.title}>Báo cáo của bé</Text></View><Pressable style={styles.childPill}><Text style={styles.childEmoji}>🧒</Text><Text style={styles.childName}>Minh Anh</Text><Ionicons name="chevron-down" size={15} color={C.primary} /></Pressable></View><View style={styles.rangeRow}>{['Tuần này', 'Tháng này', 'Tùy chỉnh'].map((item) => <Pressable key={item} onPress={() => setRange(item)} style={[styles.range, range === item && styles.rangeActive]}><Text style={[styles.rangeText, range === item && styles.rangeTextActive]}>{item}</Text></Pressable>)}</View><View style={styles.statsRow}><Metric value="34/40" label="Nhiệm vụ" icon="checkmark-circle" color={C.green} /><Metric value="85%" label="Hoàn thành" icon="trending-up" color={C.primary} /><Metric value="+420" label="XP nhận được" icon="star" color={C.orange} /></View><View style={styles.sectionHeader}><Text style={L.sectionTitle}>Tiến độ kỹ năng</Text><Text style={styles.smallLink}>Xem chi tiết</Text></View><View style={[L.card, styles.chartCard]}>{skills.map((skill) => <View key={skill.name} style={styles.skillRow}><View style={styles.skillHeader}><Text style={styles.skillName}>{skill.name}</Text><Text style={[styles.skillValue, { color: skill.color }]}>{skill.value}%</Text></View><View style={styles.skillTrack}><View style={[styles.skillFill, { width: `${skill.value}%`, backgroundColor: skill.color }]} /></View></View>)}<View style={styles.chartFooter}><Text style={styles.chartHint}>So với tuần trước</Text><View style={styles.up}><Ionicons name="arrow-up" size={13} color={C.green} /><Text style={styles.upText}>+8%</Text></View></View></View><View style={styles.sectionHeader}><Text style={L.sectionTitle}>Hoạt động tuần này</Text><Ionicons name="ellipsis-horizontal" size={20} color={C.muted} /></View><View style={[L.card, styles.activityCard]}>{[['T2', 0.78], ['T3', 0.55], ['T4', 0.91], ['T5', 0.66], ['T6', 0.84], ['T7', 0.48], ['CN', 0.32]].map(([day, height]) => <View key={day as string} style={styles.barWrap}><View style={styles.barTrack}><View style={[styles.bar, { height: `${(height as number) * 100}%`, backgroundColor: day === 'T4' ? C.primary : C.primarySoft }]} /></View><Text style={styles.day}>{day}</Text></View>)}</View><View style={styles.insight}><Text style={styles.insightIcon}>🏆</Text><View><Text style={styles.insightTitle}>Tuần này xuất sắc!</Text><Text style={styles.insightBody}>Bé đã hoàn thành nhiều hơn 12% so với tuần trước.</Text></View></View></ScrollView>;
}
function Metric({ value, label, icon, color }: { value: string; label: string; icon: any; color: string }) { return <View style={styles.metric}><Ionicons name={icon} size={20} color={color} /><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 8, marginBottom: 17 }, overline: { color: C.primary, fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, title: { color: C.text, fontSize: 26, fontWeight: '800', marginTop: 3 }, childPill: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 999, padding: 6, paddingRight: 10 }, childEmoji: { fontSize: 19 }, childName: { color: C.text, fontSize: 11, fontWeight: '700' }, rangeRow: { flexDirection: 'row', backgroundColor: '#ECEFF8', borderRadius: 12, padding: 3, marginBottom: 18 }, range: { flex: 1, paddingVertical: 9, alignItems: 'center', borderRadius: 9 }, rangeActive: { backgroundColor: C.surface }, rangeText: { color: C.muted, fontSize: 11, fontWeight: '700' }, rangeTextActive: { color: C.primary }, statsRow: { flexDirection: 'row', gap: 9, marginBottom: 25 }, metric: { flex: 1, alignItems: 'center', backgroundColor: C.surface, borderRadius: 16, borderWidth: 1, borderColor: C.border, paddingVertical: 12 }, metricValue: { color: C.text, fontSize: 16, fontWeight: '800', marginTop: 7 }, metricLabel: { color: C.muted, fontSize: 10, marginTop: 3 }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, smallLink: { color: C.primary, fontSize: 11, fontWeight: '700' }, chartCard: { padding: 17, marginBottom: 24 }, skillRow: { marginBottom: 15 }, skillHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 7 }, skillName: { color: C.text, fontSize: 12, fontWeight: '700' }, skillValue: { fontSize: 12, fontWeight: '800' }, skillTrack: { height: 9, backgroundColor: '#EFF1F7', borderRadius: 5, overflow: 'hidden' }, skillFill: { height: '100%', borderRadius: 5 }, chartFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 7, borderTopWidth: 1, borderTopColor: C.border }, chartHint: { color: C.muted, fontSize: 11 }, up: { flexDirection: 'row', gap: 3, alignItems: 'center' }, upText: { color: C.green, fontSize: 11, fontWeight: '800' }, activityCard: { height: 180, padding: 18, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end', marginBottom: 16 }, barWrap: { alignItems: 'center', height: 130, justifyContent: 'flex-end' }, barTrack: { height: 108, width: 21, borderRadius: 10, backgroundColor: '#F0F2F8', justifyContent: 'flex-end', overflow: 'hidden' }, bar: { width: '100%', borderRadius: 10 }, day: { color: C.muted, fontSize: 10, marginTop: 8 }, insight: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.orangeSoft, borderRadius: 16, padding: 15 }, insightIcon: { fontSize: 28 }, insightTitle: { color: '#8A5A05', fontSize: 13, fontWeight: '800' }, insightBody: { color: '#9B7639', fontSize: 11, marginTop: 3 } });
