import { StyleSheet, Platform } from 'react-native';

export const COLORS = {
  primary: '#2B44E8',
  primaryDark: '#1A298C',
  background: '#F8F9FE',
  white: '#FFFFFF',
  textDark: '#1B205D',
  textLight: '#8B95B7',
  textGray: '#A0A7C0',
  lightBlue: '#E8EDFC',
  aiDuyetBg: '#5470F2',
  daDuyetBg: '#C6D4F9',
  daDuyetText: '#2B44E8',
  dangThucHienBg: '#84B022',
  tagVeSinhBg: '#FFF3E0',
  tagVeSinhText: '#D28A36',
  tagSapXepBg: '#FFF3E0', // Using same for now, can be adjusted
  tagSapXepText: '#D28A36',
  starText: '#FFA900',
  xpBg: '#F2E8FF',
  xpText: '#8E54E9',
  buttonLightBg: '#C6D4F9',
  buttonLightText: '#2B44E8',
  redIcon: '#FF4D4F',
  redBg: '#FFF1F0',
  progressBg: '#E2E8F0',
  progressFill: '#84B022',
  itemBg: '#FFFFFF',
  iconContainerBg: '#F0F2F8',
  iconContainerActiveBg: '#C9ED3A',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 40 : 10,
    paddingBottom: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.lightBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  addButtonText: {
    color: COLORS.white,
    fontWeight: '600',
    marginLeft: 4,
    fontSize: 14,
  },
  weekSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.lightBlue,
    marginHorizontal: 20,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  weekSelectorCenter: {
    alignItems: 'center',
  },
  weekSelectorLabel: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 4,
  },
  weekSelectorDate: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: 'bold',
  },
  calendarStrip: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  dayCol: {
    alignItems: 'center',
  },
  dayName: {
    fontSize: 12,
    color: COLORS.textLight,
    marginBottom: 8,
    fontWeight: '500',
  },
  dayCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayCircleActive: {
    backgroundColor: COLORS.primary,
  },
  dayDate: {
    fontSize: 16,
    color: COLORS.textDark,
    fontWeight: '600',
  },
  dayDateActive: {
    color: COLORS.white,
  },
  dayDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.white,
    marginTop: 2,
  },
  dayDotInactive: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.primary,
    marginTop: 2,
  },
  filtersContainer: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  filterItem: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: COLORS.lightBlue,
    marginRight: 12,
  },
  filterItemActive: {
    backgroundColor: COLORS.primary,
  },
  filterText: {
    fontSize: 13,
    color: COLORS.textLight,
    fontWeight: '600',
  },
  filterTextActive: {
    color: COLORS.white,
  },
  taskList: {
    paddingHorizontal: 20,
    paddingBottom: 100, // padding for bottom tab
  },
  taskCard: {
    backgroundColor: COLORS.itemBg,
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  taskRow1: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  taskIconBox: {
    width: 64,
    height: 64,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  taskEmoji: {
    fontSize: 32,
  },
  taskInfo: {
    flex: 1,
  },
  taskTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 4,
  },
  taskTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  taskTimeText: {
    fontSize: 12,
    color: COLORS.textLight,
    marginLeft: 4,
  },
  taskTagsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tagStar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF8E1',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    marginRight: 6,
  },
  tagStarText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: COLORS.starText,
    marginLeft: 2,
  },
  tagXp: {
    backgroundColor: COLORS.xpBg,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    marginRight: 6,
  },
  tagXpText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: COLORS.xpText,
  },
  tagCategory: {
    backgroundColor: COLORS.tagVeSinhBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  tagCategoryText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: COLORS.tagVeSinhText,
  },
  statusContainer: {
    alignItems: 'flex-end',
  },
  statusButtonAiDuyet: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.aiDuyetBg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  statusButtonAiDuyetText: {
    color: COLORS.white,
    fontSize: 11,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  statusBadgeDaDuyet: {
    backgroundColor: COLORS.daDuyetBg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  statusBadgeDaDuyetText: {
    color: COLORS.daDuyetText,
    fontSize: 11,
    fontWeight: 'bold',
  },
  statusBadgeDangThucHien: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.dangThucHienBg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  statusBadgeDangThucHienText: {
    color: COLORS.white,
    fontSize: 11,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  progressRow: {
    marginBottom: 16,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  progressLabel: {
    fontSize: 12,
    color: COLORS.textDark,
    fontWeight: '600',
  },
  progressPercent: {
    fontSize: 12,
    color: COLORS.dangThucHienBg,
    fontWeight: 'bold',
  },
  progressBarBg: {
    height: 8,
    backgroundColor: COLORS.progressBg,
    borderRadius: 4,
  },
  progressBarFill: {
    height: 8,
    backgroundColor: COLORS.progressFill,
    borderRadius: 4,
  },
  taskRow2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  actionButtonXem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.buttonLightBg,
    paddingVertical: 12,
    borderRadius: 20,
    marginRight: 12,
  },
  actionButtonXemText: {
    color: COLORS.buttonLightText,
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 6,
  },
  actionButtonKiemTra: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 20,
    marginRight: 12,
  },
  actionButtonKiemTraText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 14,
  },
  actionIconBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.buttonLightBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionIconBtnRed: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.redIcon,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // --- Modal Styles ---
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  modalSubtitle: {
    fontSize: 14,
    color: COLORS.textLight,
    marginTop: 4,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.lightBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressBarContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  progressSegment: {
    flex: 1,
    height: 4,
    backgroundColor: COLORS.lightBlue,
    borderRadius: 2,
    marginHorizontal: 4,
  },
  progressSegmentActive: {
    backgroundColor: COLORS.primary,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 12,
    marginTop: 16,
  },
  // Step 1
  timeInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  timeInputBox: {
    backgroundColor: '#F4F6FB',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    width: 65,
    alignItems: 'center',
  },
  timeInputText: {
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: '500',
  },
  timeSeparator: {
    fontSize: 16,
    color: COLORS.textLight,
    fontWeight: 'bold',
  },
  // Step 2
  textInput: {
    backgroundColor: '#F4F6FB',
    borderRadius: 16,
    padding: 16,
    fontSize: 15,
    color: COLORS.textDark,
    marginBottom: 8,
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 8,
  },
  iconBox: {
    width: 50,
    height: 50,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconBoxActive: {
    backgroundColor: COLORS.iconContainerActiveBg,
    borderWidth: 1.5,
    borderColor: '#A1C71F',
  },
  iconText: {
    fontSize: 24,
  },
  iconAddBox: {
    backgroundColor: '#F4F6FB',
  },
  skillsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  skillTag: {
    backgroundColor: '#FCF3FA',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  skillTagText: {
    color: '#D85CD2',
    fontWeight: 'bold',
    fontSize: 13,
  },
  rewardsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  rewardBox: {
    backgroundColor: '#F4F6FB',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    flexDirection: 'row',
  },
  // Step 3
  textArea: {
    backgroundColor: '#F4F6FB',
    borderRadius: 16,
    padding: 16,
    height: 120,
    textAlignVertical: 'top',
    fontSize: 15,
    color: COLORS.textDark,
  },
  // Step 4
  aiConfirmBox: {
    backgroundColor: '#F4F6FB',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  aiConfirmTextGroup: {
    marginLeft: 12,
    flex: 1,
  },
  aiConfirmTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  aiConfirmDesc: {
    fontSize: 13,
    color: COLORS.textLight,
    marginTop: 4,
  },
  aiLoadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  aiLoadingCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#4A62FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#8E54E9',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  aiLoadingText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: '500',
  },
  aiVideoThumbnail: {
    width: '100%',
    height: 200,
    borderRadius: 16,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    marginBottom: 24,
  },
  // Primary Button
  primaryButton: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
    borderRadius: 30,
    marginTop: 24,
  },
  primaryButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 8,
  },
});
